name: Auto-login-Lunes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 */6 * *' # 每隔 14 天在 UTC 1:00 (北京时间 9:00) 运行

jobs:
  Renew-lunes:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 📥 下载代码
        uses: actions/checkout@v4

      - name: 🐍 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 🛠️ 安装系统依赖和 Python 依赖
        run: |
          sudo apt-get update
          sudo apt-get install xvfb x11-utils xdotool scrot fonts-noto-cjk -y
          pip install seleniumbase aiohttp requests
          seleniumbase install chromedriver

      - name: 🚀 运行续期脚本
        env:
          LUNES_EMAIL: ${{ secrets.LUNES_EMAIL }}
          LUNES_PASSWORD: ${{ secrets.LUNES_PASSWORD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
            python3 app.py
